"""Add JobHistory table

Revision ID: 25163d3a0baa
Revises: 8c5ec83f3c1b
Create Date: 2025-12-21 00:07:59.658793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25163d3a0baa'
down_revision: Union[str, None] = '8c5ec83f3c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_history',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_job_history_changed_by_id_users')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_history_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_history'))
    )
    op.create_index(op.f('ix_job_history_id'), 'job_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_history_id'), table_name='job_history')
    op.drop_table('job_history')
    # ### end Alembic commands ###
