"""add_undo_redo_versioning

Revision ID: 8c95b040e546
Revises: 25163d3a0baa
Create Date: 2025-12-21 20:22:20.829924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c95b040e546'
down_revision: Union[str, None] = '25163d3a0baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_history', sa.Column('version', sa.Integer(), nullable=False))
    op.drop_index('ix_job_history_id', table_name='job_history')
    op.add_column('jobs', sa.Column('current_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'current_version')
    op.create_index('ix_job_history_id', 'job_history', ['id'], unique=False)
    op.drop_column('job_history', 'version')
    # ### end Alembic commands ###
